/* 구매내역 조회 : 뷰 생성 */

/* 번호(거래내역번호) 상품명 구매일 구매지점 수량 가격 적립P */
SELECT USER_NO, PRODUCT_NAME, STORE_NAME, PURCHASE_QUANTITY, CALCULATED_PRICE, ACCUMULATE_POINT  FROM TB_PURCHASE
JOIN TB_USER USING(USER_NO)
JOIN TB_STORE_PRODUCT USING(STORE_PRODUCT_NO)
JOIN TB_STORE ON(TB_STORE_PRODUCT.STORE_NO=TB_STORE.STORE_NO)
JOIN TB_PRODUCT USING(PRODUCT_NO);