/* 구매내역 조회 : 뷰 */

/* 번호(거래내역번호) 상품명 구매일 구매지점 수량 가격 적립P */
SELECT USER_NO, PRODUCT_NAME, STORE_NAME, PURCHASE_QUANTITY, CALCULATED_PRICE, ACCUMULATE_POINT  FROM TB_PURCHASE
JOIN TB_USER USING(USER_NO)
JOIN TB_STORE_PRODUCT USING(STORE_PRODUCT_NO)
JOIN TB_STORE ON(TB_STORE_PRODUCT.STORE_NO=TB_STORE.STORE_NO)
JOIN TB_PRODUCT USING(PRODUCT_NO);

/* 기프티콘보관함 = 기프티콘 +구매 +사용자 +지점상품  */

SELECT GIFTICON_NO  FROM TB_GIFTICON
JOIN TB_PURCHASE USING (PURCHASE_NO)
JOIN TB_USER USING (USER_NO)
JOIN TB_STORE_PRODUCT USING  (STORE_PRODUCT_NO)
;



























/* 실시간 인기상품 리스트 TOP3 : 뷰 */
/* 
인기상품 = 구매내역이 가장 많은 상품 
3사의 모든 상품을 대상으로 함

조회 내용 : 상호명, 상품명, 구매횟수 
*/
SELECT BRAND_NAME, PRODUCT_NAME, COUNT(*) AS PURCHASE_COUNT
FROM TB_PURCHASE
JOIN TB_STORE_PRODUCT USING(STORE_PRODUCT_NO)
JOIN TB_PRODUCT USING(PRODUCT_NO)
JOIN TB_BRAND USING(BRAND_NO)
GROUP BY BRAND_NAME,PRODUCT_NAME
ORDER BY 3 DESC;

/**/

