/* 자유게시판 뷰 */
/*
CREATE VIEW BOARD_VIEW AS
*/
SELECT A.BOARD_NO, A.TITLE, A.WRITER, B.USER_NAME, A.CONTENTS, A.WRITE_DATE, A.READCOUNT, A.ORIGINAL_FILE_NAME, A.STORED_FILE_NAME, A.DEL_CHECK
FROM TB_BOARD A
JOIN TB_USER B ON(A.WRITER = B.USER_NO);


/* 상호 > vo */


/* 할인 > vo */


/* 할인상품 뷰 */
/*
CREATE VIEW DC_PRODUCT_VIEW AS
*/
SELECT A.STORE_NO, A.PRODUCT_NO, A.DISCOUNT_NO, B.DISCOUNT_NAME, A.DISCOUNT_INFO
FROM TB_DC_PRODUCT A
JOIN TB_DC_INFO B ON(A.DISCOUNT_NO = B.DISCOUNT_NO);


/* 이벤트 뷰 */
/*
CREATE VIEW EVENT_VIEW AS
*/
SELECT A.EVENT_NO, A.TITLE, A.WRITER, B.USER_NAME, A.CONTENTS, A.START_DATE, A.END_DATE, A.JOIN_LIMIT, A.READCOUNT, A.ORIGINAL_FILE_NAME,
A.STORED_FILE_NAME, B.BRAND_NO, A.DEL_CHECK FROM TB_EVENT A JOIN TB_USER B ON(A.WRITER = B.USER_NO);


/*이벤트 참여 > vo */


/* 이벤트 결과 뷰*/
/*
CREATE VIEW EVENT_RESULT_VIEW AS
*/
SELECT A.EVENT_RESULT_NO, A.EVENT_NO, A.TITLE, A.WRITER, B.USER_NAME, A.CONTENTS, A.WRITE_DATE, A.READCOUNT, A.ORIGINAL_FILE_NAME,
A.STORED_FILE_NAME, B.BRAND_NO, A.DEL_CHECK FROM TB_EVENT_RESULT A JOIN TB_USER B ON(A.WRITER = B.USER_NO);


/* 이벤트 결과 이벤트참여리스트 뷰 */
/*
CREATE VIEW EVENT_JOIN_USER_VIEW AS
*/
SELECT EVENT_NO, USER_NO, USER_NAME FROM TB_EVENT_JOIN
JOIN TB_USER USING(USER_NO);


/* 관심목록 = 사용자 +지점 +상품 */
/* 
사용자 번호, 상호번호, 지점번호, 지점명, 상품번호, 상품명,  상품이미지
*/
/*
CREATE VIEW FAVORITE_LIST_VIEW AS
*/
SELECT USER_NO, A.BRAND_NO, D.BRAND_NAME , A.STORE_NO, STORE_NAME, B.PRODUCT_NO, B.PRODUCT_NAME, B.STORED_FILE_NAME,  
STORE_PRODUCT_NO, TRUNC(MIN(C.MANUFACTURE_DATE+B.EXPIRATION_DATE-SYSDATE)*24) AS MIN_EXPIRATION_HOUR
FROM TB_FAVORITE_LIST
JOIN TB_STORE A ON(A.STORE_NO = TB_FAVORITE_LIST.STORE_NO)
JOIN TB_PRODUCT B ON(B.PRODUCT_NO = TB_FAVORITE_LIST.PRODUCT_NO)
JOIN TB_STORE_PRODUCT C ON(A.STORE_NO = C.STORE_NO AND B.PRODUCT_NO = C.PRODUCT_NO)
JOIN TB_BRAND D ON(A.BRAND_NO=D.BRAND_NO)
GROUP BY USER_NO, A.BRAND_NO,  D.BRAND_NAME, A.STORE_NO, STORE_NAME, B.PRODUCT_NO, B.PRODUCT_NAME, B.STORED_FILE_NAME,  
STORE_PRODUCT_NO;


/* 기프티콘보관함 = 기프티콘 +구매 +사용자 +지점상품  */
/*  
기프티콘번호, 사용자번호, 상품 이미지, 상호번호,  지점번호, 지점명, 상품번호, 상품명, 구매수량, 기프티콘 소멸날짜extinction_date(제조일+유통기한) ,사용여부, 바코드이미지명
*/
/*
CREATE VIEW GIFTICON_VIEW AS
*/
SELECT A.GIFTICON_NO, B.USER_NO, E.STORED_FILE_NAME, E.BRAND_NO, 
D.STORE_NO, D.STORE_NAME, E.PRODUCT_NO, E.PRODUCT_NAME, B.PURCHASE_QUANTITY,
C.MANUFACTURE_DATE+E.EXPIRATION_DATE AS EXTINCTION_DATE, --기프티콘 만료날짜--
A.IS_USE, A.BARCODE_IMG_NAME 
FROM TB_GIFTICON A
JOIN TB_PURCHASE B USING (PURCHASE_NO)
JOIN TB_STORE_PRODUCT C USING (STORE_PRODUCT_NO)
JOIN TB_STORE D ON (D.STORE_NO = C.STORE_NO)
JOIN TB_PRODUCT E ON (E.PRODUCT_NO = C.PRODUCT_NO)
JOIN TB_BRAND F ON(E.BRAND_NO = F.BRAND_NO);

/* 상품 > vo */


/* 상품 종류 > vo */


/* 구매내역 조회 : 뷰 */

/* 번호(거래내역번호) 상품명 구매일 구매지점 수량 가격 적립P */

/*
CREATE VIEW PURCHASE_RECODE_VIEW AS
*/
SELECT USER_NO, PRODUCT_NAME, STORE_NAME, PURCHASE_QUANTITY, CALCULATED_PRICE, ACCUMULATE_POINT  
FROM TB_PURCHASE
JOIN TB_USER USING(USER_NO)
JOIN TB_STORE_PRODUCT USING(STORE_PRODUCT_NO)
JOIN TB_STORE ON(TB_STORE_PRODUCT.STORE_NO=TB_STORE.STORE_NO)
JOIN TB_PRODUCT USING(PRODUCT_NO);


/* 고객센터 문의 뷰 */
/*
CREATE VIEW SERVICE_CENTER_VIEW AS
*/
SELECT A.SERVICE_NO, A.TITLE, A.WRITER, B.USER_NAME, A.CONTENTS, A.WRITE_DATE, A.READCOUNT, A.ORIGINAL_FILE_NAME, 
A.STORED_FILE_NAME, A.DEL_CHECK
FROM TB_SERVICE_CENTER A
JOIN TB_USER B ON(A.WRITER = B.USER_NO);


/* 고객센터 문의 댓글 뷰 */
/*
CREATE VIEW SERVICE_CENTER_COMMENT_VIEW AS
*/
SELECT A.SERVICE_COMMENT_NO, A.SERVICE_NO, A.WRITER, B.USER_NAME, A.CONTENTS, A.WRITE_DATE, A.DEL_CHECK
FROM TB_SERVICE_CENTER_COMMENT A
JOIN TB_USER B ON(A.WRITER = B.USER_NO);


/* 지점 > vo */

---------

/* 지점 상품 리스트 인기상품포함 뷰*/
/* 지점상품번호 지점번호 상품번호 상품명 제조사 가격 제조일 유통기한(계산된날짜) 재고 상품종류번호 상호번호 첨부파일변경명 삭제구분 */
/*
CREATE VIEW STORE_PRODUCT_VIEW AS
*/
SELECT A.STORE_PRODUCT_NO, A.STORE_NO, A.PRODUCT_NO, B.PRODUCT_NAME, B.MANUFACTURER, B.PRICE, A.MANUFACTURE_DATE, B.EXPIRATION_DATE,
TRUNC((A.MANUFACTURE_DATE+B.EXPIRATION_DATE-SYSDATE)*24,0) AS EXPIRATION_HOUR, A.QUANTITY, B.PRODUCT_KIND_NO, F.PRODUCT_KIND_NAME, B.BRAND_NO,
B.ORIGINAL_FILE_NAME, B.STORED_FILE_NAME, B.DEL_CHECK,
(SELECT COUNT(*) 
FROM TB_PURCHASE C 
JOIN TB_STORE_PRODUCT D ON(C.STORE_PRODUCT_NO = D.STORE_PRODUCT_NO)
JOIN TB_PRODUCT E ON(D.PRODUCT_NO = E.PRODUCT_NO)
WHERE E.PRODUCT_NO = A.PRODUCT_NO AND D.STORE_NO = A.STORE_NO) AS PURCHASE_COUNT
FROM TB_STORE_PRODUCT A
JOIN TB_PRODUCT B ON (A.PRODUCT_NO = B.PRODUCT_NO)
JOIN TB_PRODUCT_KIND F ON (B.PRODUCT_KIND_NO = F.PRODUCT_KIND_NO);

/* 지점 할인상품 리스트 인기상품포함 뷰*/
/*
CREATE VIEW STORE_POPULARITY_PRODUCT_VIEW AS
*/
-- STORE_PRODUCT VO
SELECT A.STORE_PRODUCT_NO, A.STORE_NO, A.PRODUCT_NO, B.PRODUCT_NAME, B.MANUFACTURER, B.PRICE, A.MANUFACTURE_DATE, B.EXPIRATION_DATE,
TRUNC((A.MANUFACTURE_DATE+B.EXPIRATION_DATE-SYSDATE)*24,0) AS EXPIRATION_HOUR, A.QUANTITY, B.PRODUCT_KIND_NO, F.PRODUCT_KIND_NAME, B.BRAND_NO,
B.ORIGINAL_FILE_NAME, B.STORED_FILE_NAME, B.DEL_CHECK,
(SELECT COUNT(*) 
FROM TB_PURCHASE C 
JOIN TB_STORE_PRODUCT D ON(C.STORE_PRODUCT_NO = D.STORE_PRODUCT_NO)
JOIN TB_PRODUCT E ON(D.PRODUCT_NO = E.PRODUCT_NO)
WHERE E.PRODUCT_NO = A.PRODUCT_NO AND D.STORE_NO = A.STORE_NO) AS PURCHASE_COUNT,
DISCOUNT_NO, DISCOUNT_INFO
FROM TB_STORE_PRODUCT A
JOIN TB_PRODUCT B ON (A.PRODUCT_NO = B.PRODUCT_NO)
JOIN TB_PRODUCT_KIND F ON (B.PRODUCT_KIND_NO = F.PRODUCT_KIND_NO)
JOIN TB_DC_PRODUCT G ON (A.PRODUCT_NO = G.PRODUCT_NO AND A.STORE_NO = G.STORE_NO);

-------------------


/* 전체 상품 리스트에서의 인기상품포함 뷰 */
/* 
인기상품 = 구매내역이 가장 많은 상품 
3사의 모든 상품을 대상으로 함

조회 내용 : 상호명, 상품명, 구매횟수 
*/

SELECT A.PRODUCT_NO, A.PRODUCT_NAME, A.MANUFACTURER, A.PRICE, A.EXPIRATION_DATE, A.PRODUCT_KIND_NO, E.PRODUCT_KIND_NAME,
A.BRAND_NO, A.ORIGINAL_FILE_NAME, A.STORED_FILE_NAME,
A.DEL_CHECK, 
(SELECT COUNT(*) 
FROM TB_PURCHASE B 
JOIN TB_STORE_PRODUCT C ON(B.STORE_PRODUCT_NO = C.STORE_PRODUCT_NO)
JOIN TB_PRODUCT D ON(C.PRODUCT_NO = D.PRODUCT_NO)
WHERE D.PRODUCT_NO = A.PRODUCT_NO) AS PURCHASE_COUNT
FROM TB_PRODUCT A
JOIN TB_PRODUCT_KIND E ON (A.PRODUCT_KIND_NO = E.PRODUCT_KIND_NO);


/* 지점 뷰 */
SELECT  A.*, B.BRAND_NAME
FROM TB_STORE A
JOIN TB_BRAND B ON(A.BRAND_NO = B.BRAND_NO);


/* 판매내역 */ 
SELECT A.PURCHASE_NO SALE_NO, D.STORE_NO, D.BRAND_NO, E.PRODUCT_NO, E.PRODUCT_NAME,E.PRODUCT_KIND_NO, A.PURCHASE_QUANTITY SALE_QUANTITY, 
A.CALCULATED_PRICE, A.USING_POINT, A.PURCHASE_DATE SALE_DATE, B.USER_NO, B.USER_NAME, SUBSTR(B.PHONE,-4) AS PHONE_NICK
FROM TB_PURCHASE A 
JOIN TB_USER B ON(A.USER_NO = B.USER_NO)
JOIN TB_STORE_PRODUCT C ON(A.STORE_PRODUCT_NO = C.STORE_PRODUCT_NO)
JOIN TB_STORE D ON(C.STORE_NO = D.STORE_NO)
JOIN TB_PRODUCT E ON(C.PRODUCT_NO = E.PRODUCT_NO);

/*종류별 판매량*/
SELECT C.STORE_NO, C.BRAND_NO, D.PRODUCT_KIND_NO, E.PRODUCT_KIND_NAME,SUM(A.PURCHASE_QUANTITY) AS SALE_QUANTITY
FROM TB_PURCHASE A 
JOIN TB_STORE_PRODUCT B ON(A.STORE_PRODUCT_NO = B.STORE_PRODUCT_NO)
JOIN TB_STORE C ON(B.STORE_NO = C.STORE_NO)
JOIN TB_PRODUCT D ON(B.PRODUCT_NO = D.PRODUCT_NO)
JOIN TB_PRODUCT_KIND E ON(D.PRODUCT_KIND_NO = E.PRODUCT_KIND_NO)
GROUP BY C.STORE_NO, C.BRAND_NO,D.PRODUCT_KIND_NO,E.PRODUCT_KIND_NAME;



