
--TB_SERVICE_CENTER
INSERT INTO TB_SERVICE_CENTER VALUES(1,'이벤트는 언제하나요', ?,'이벤트는 언제하나요', SYSDATE,1 , NULL, NULL,'N' );
INSERT INTO TB_SERVICE_CENTER VALUES(2,'회원가입오류', ?,'회원가입이 안됩니다.', SYSDATE, 2 , NULL, NULL,'N' );
INSERT INTO TB_SERVICE_CENTER VALUES(3,'이벤트 어디서 볼수 있나요.', ?,'이벤트 어디서 볼수 있나요.', SYSDATE,3 , NULL, NULL,'N' );
INSERT INTO TB_SERVICE_CENTER VALUES(4,'아이디/패스워드를 찾을수 없습니다', ?,'아이디/패스워드를 찾을수 없습니다', SYSDATE,3 , NULL, NULL,'N' );
INSERT INTO TB_SERVICE_CENTER VALUES(5,'이벤트당첨발표 언제인가요??', ?,'이벤트당첨발표 언제인가요??.', SYSDATE,3 , NULL, NULL,'N' );
INSERT INTO TB_SERVICE_CENTER VALUES(6,'내 정보변경은 어디서 할 수 있나요', ?,'로그인후 마이페이지에서 변경할 수 있습니다', SYSDATE,3 , NULL, NULL,'N' );
INSERT INTO TB_SERVICE_CENTER VALUES(7,'고객의 아이디가 휴면상태로뜹니다', ?,'6개월이상 미이용시 휴면상태가 됩니다.', SYSDATE,3 , NULL, NULL,'N' );

DELETE FROM TB_SERVICE_CENTER;

--TB_SERVICE_CENTER_COMMENT
INSERT INTO TB_SERVICE_CENTER_COMMENT VALUES(1,1,NULL,'매월1회 하고있습니다',SYSDATE,'N');
INSERT INTO TB_SERVICE_CENTER_COMMENT VALUES(1,2,NULL,'입력정보를 전부 작성해 주세요',SYSDATE,'N');
INSERT INTO TB_SERVICE_CENTER_COMMENT VALUES(1,3,NULL,'메인페이지에 있습니다.',SYSDATE,'N');
INSERT INTO TB_SERVICE_CENTER_COMMENT VALUES(1,4,NULL,'홈페이지상에 등록된 고객정보 중 일부가 일치 하지 않는 경우 입니다.',SYSDATE,'N');
INSERT INTO TB_SERVICE_CENTER_COMMENT VALUES(1,5,NULL,'3일후 이벤트 당첨 발표입니다.',SYSDATE,'N');
INSERT INTO TB_SERVICE_CENTER_COMMENT VALUES(1,6,NULL,'로그인후 마이페이지에서 변경할 수 있습니다',SYSDATE,'N');
INSERT INTO TB_SERVICE_CENTER_COMMENT VALUES(1,7,NULL,'6개월이상 미이용시 휴면상태가 됩니다..',SYSDATE,'N');

DELETE FROM TB_SERVICE_CENTER_COMMENT;
